### ISSUE TITLE
FL: Fetching LDOT coin on Acala blockchain keeps causing an error

### ISSUE THREAD

**Issue by AMIRKHANEF** [PolkaGate/extension#1048]
![image](https://github.com/PolkaGate/extension/assets/75857984/1d54088a-c6d2-4316-bbbe-d331612c4826)

![image](https://github.com/PolkaGate/extension/assets/75857984/0f0313a0-4b2f-4ad7-9afc-bf3e9681264f)

**Comment by Nick-1979** [comment]
fixed
