### ISSUE TITLE
using themeColors instead

### ISSUE THREAD

**Issue by Nick-1979** [PolkaGate/extension#1054]
like what we have used for dividerColor we can apply the similar for

  const indexBgColor = useMemo(() => theme.palette.mode === 'light' ? '#DFDFDF' : theme.palette.background.paper, [theme.palette]);
  const contentBgColor = useMemo(() => theme.palette.mode === 'light' ? '#F1F1F1' : theme.palette.background.default, [theme.palette]);

**Comment by AMIRKHANEF** [comment]
**WORK IN PROGRESS**
