### ISSUE TITLE
AccountDetailsFS: History modal does not work properly on different chains

### ISSUE THREAD

**Issue by AMIRKHANEF** [PolkaGate/extension#1077]

**Comment by Nick-1979** [comment]
any screenshots

**Comment by AMIRKHANEF** [comment]
@Nick-1979 
![image](https://github.com/PolkaGate/extension/assets/75857984/9d35c9ae-6dcf-47d6-ad82-24c9ddbd57cb)

**Comment by AMIRKHANEF** [comment]
**WORK IN PROGRESS**
