### ISSUE TITLE
(Extension) Feature Request: Fullscreen for FirstTimeSetPassword.tsx

### ISSUE THREAD

**Issue by 0xLiquidGlass** [PolkaGate/extension#1088]
## Context
Hi devs, I would like to request a feature for the login password page to be fullscreen by default

This feature will allow the user to input the password and focus on other applications without the popup disappearing upon returning back to the browser

## Code
This is the link to my fork of the extension repo with the modified FirstTimeSetPassword.tsx:
[https://github.com/0xLiquidGlass/polkagate-extension/blob/dev-liquidglass/packages/extension-polkagate/src/popup/passwordManagement/FirstTimeSetPassword.tsx](https://github.com/0xLiquidGlass/polkagate-extension/blob/dev-liquidglass/packages/extension-polkagate/src/popup/passwordManagement/FirstTimeSetPassword.tsx)

**Note: I am not able to test the code due to memory limitations and would require help in testing the modified code**

## Flow
This is how the flow will look like when implemented:

1. Greeted with the "Would you like to set a login password?" page
2. If the user clicks on "Yes", it will direct the user to set a login password page on fullscreen
3. Then the rest (i.e. account creation, import) will be the same

Currently, the login password page is only a popup and can disappear if other applications is being used and then returning back to the browser

**Comment by 0xLiquidGlass** [comment]
Changes in FirstTimeSetPassword.tsx

- Added `useFullscreen();` below `function FirstTimeSetPassword()`,
- Modified to use `import { useFullscreen, useTranslation } from '../../hooks';` instead of `import { useTranslation } from '../../hooks'`;

**Comment by Nick-1979** [comment]
Polkagate FullScreen is coming hopefully very soon, then you will have your order embedded as well!

Thank you,
