### ISSUE TITLE
SOLO STAKING FS: Cannot convert undefined or null to object ::BUG

### ISSUE THREAD

**Issue by AMIRKHANEF** [PolkaGate/extension#1111]
when account has not solo staked

![image](https://github.com/PolkaGate/extension/assets/75857984/24c7af75-8eef-4e64-9aee-f561d468cc6b)

due to this line of code:
![image](https://github.com/PolkaGate/extension/assets/75857984/ba6d522a-5d5d-4699-949e-d5c84354c38f)

**Comment by Nick-1979** [comment]
fixed
