### ISSUE TITLE
can remove chain as a ThroughProxy props?

### ISSUE THREAD

**Issue by Nick-1979** [PolkaGate/extension#1113]
use useChain hook instead

**Comment by AMIRKHANEF** [comment]
**WORK IN PROGRESS**

**Comment by AMIRKHANEF** [comment]
No, it's not possible. **useChain** will return the proxy account's chain, which might be on a different network. In such cases, the address format type and **identicon** will be different!

**Comment by AMIRKHANEF** [comment]
![image](https://github.com/PolkaGate/extension/assets/75857984/392fa766-2948-4ce9-98da-0d54687e7bbf)

**Comment by AMIRKHANEF** [comment]
@Nick-1979

**Comment by Nick-1979** [comment]
ok, so if it is necessary i close this issue
