### ISSUE TITLE
FS: user who unstake all their assets from nomination pools

### ISSUE THREAD

**Issue by AMIRKHANEF** [PolkaGate/extension#1164]
when a user withdraw all his redeemable assets from pool, what should we display then?
maybe account details, maybe stake options!

![image](https://github.com/PolkaGate/extension/assets/75857984/7f4ec3c6-8887-469b-a914-da18947e38d3)

**Comment by Nick-1979** [comment]
@AMIRKHANEF  We currently shows this page with stake button enabled if they have some tokens available
