### ISSUE TITLE
handle api derive account in other placess

### ISSUE THREAD

**Issue by Nick-1979** [PolkaGate/extension#1227]
since api derive account does not work as expected hence can be replace with other apis

**Comment by Nick-1979** [comment]
@AMIRKHANEF 

still one usage here:
    const identities = await Promise.all(poolsInfo.map((pool) => api.derive.accounts.info(pool.bondedPool.roles?.root || pool.bondedPool.roles.depositor)));

**Comment by AMIRKHANEF** [comment]
We need to decide on the necessity of the 'usePools' hook, which includes this line of code. 
If it's essential, 
we should integrate it into full-screen mode,
otherwise, consider removing it from extension mode.

**Comment by Nick-1979** [comment]
usePools has already been used in join pool FS
