### ISSUE TITLE
add Import Proxied(s) to account menu, and import menu in home screen

### ISSUE THREAD

**Issue by Nick-1979** [PolkaGate/extension#1243]
instead of adding proxied account(s) as watch only, we can import all proxied accounts of a proxy account automatically
or even let user choose from the list of proxied accounts to import if any

**Comment by AMIRKHANEF** [comment]
We can add a button on Proxy management page!

**Comment by AMIRKHANEF** [comment]
@Nick-1979 
Can be closed, already done!
