### ISSUE TITLE
delegate vote issues

### ISSUE THREAD

**Issue by Nick-1979** [PolkaGate/extension#1494]
1- click on locked amount to fill the amount input does not trigger the next button to be enabled!
2- manually selecting tracks will set scroll to top on each select which is annoying!
3- if using proxy, the confirmation page will be like:
![Screenshot 2024-08-19 at 22 59 44](https://github.com/user-attachments/assets/c2dbe560-d128-41a2-a531-067355feac2e)

**Comment by AMIRKHANEF** [comment]
we should find a better way in order to set the height of the modal!
