### ISSUE TITLE
# Enum as storage need a default attribute otherwise front end not able to read for default value

### ISSUE THREAD

**Issue by Johnnysoltani** [PolkaGate/extension#1632]
# Enum as storage need a default attribute otherwise front end not able to read for default value

## Types of change

- [x] Feature
- [X] Bug
- [x] Enhancement

_Originally posted by @ngjupeng in https://github.com/Scaffold-Stark/scaffold-stark-2/pull/342_

**Comment by Nick-1979** [comment]
The content is unclear to me
