### ISSUE TITLE
Wrong information on validators page

### ISSUE THREAD

**Issue by AMIRKHANEF** [PolkaGate/extension#1635]
This account hasn't staked yet, but it says although the validator is oversubscribed but you are on the top 64 

![image](https://github.com/user-attachments/assets/03c1049e-d5c4-483e-b817-2767218bf5b6)

**Comment by Sophiestanworth** [comment]
> This account hasn't staked yet, but it says although the validator is oversubscribed but you are on the top 64


Hello @AMIRKHANEF,

It appears your account hasn’t been staked yet, though you’re seeing a message that, despite the validator being oversubscribed, you’re within the top 64. This likely means your account is queued for staking, but no tokens have been processed. For help with the staking process, please reach out to the support team.

A support ticket (ID: PLKG7638) has been created for you. Visit [Polkagate Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat bubble at the bottom right to connect with an agent.

Thank you for your patience—I hope this gets resolved soon!

**Comment by Nick-1979** [comment]
It's just a warning!
Yes the user if selects this validator they would be on a safe place based on their staked amount already entered.
