### ISSUE TITLE
SSL certs on wallet home pages

### ISSUE THREAD

**Issue by NukeManDan** [PolkaGate/extension#357]
http://www.polkagate.xyz/ (and http://polkadotjs.plus/ ) are insecure and require users to bypass security to view them. No one should trust a wallet you have to do that for. Less so download anything from it. 

Please fix, perhaps with this easy and free resource: https://letsencrypt.org/

**Comment by PolkaGate** [comment]
Hey @NukeManDan ,

Thank you for opening the issue.
Could you please try : https://polkagate.xyz

We hope you could share the experience of using the extension with us too.
Even though we are hardly working on the new extension which will be released soon.

Cheers

**Comment by NukeManDan** [comment]
SSL seems working again :+1: I will checkout https://polkadotjs.plus/ if that is what you mean? Could try source here - is there reasoning for the change of repo? https://github.com/PolkaGate/polkadot-Js-Plus-extension I assume is the published version to be rep[laced by this repo... correct?

**Comment by PolkaGate** [comment]
Polkadot js plus (Plus) was originally born here: https://github.com/Nick-1979/polkadot-Js-Plus-extension
After receiving a Kusama treasury fund we rebranded to Polkagate, we are developing a  new extension which may finally replace Plus, but we will support plus as much as we can.
