### ISSUE TITLE
FullScreen: show a more detailed info after copying an address on home screen

### ISSUE THREAD

**Issue by Nick-1979** [PolkaGate/extension#933]

**Comment by Nick-1979** [comment]
<img width="794" alt="Screenshot 2024-02-19 at 11 47 22 at night" src="https://github.com/PolkaGate/extension/assets/46442452/f55e938e-31a5-4b03-a2a1-21378d7e71d5">

**Comment by AMIRKHANEF** [comment]
Related PR posted.

**Comment by Nick-1979** [comment]
I think its better to add a modal, where let users to choose a chain to copy its associated address. This will be more straightforward way of copying address.

**Comment by AMIRKHANEF** [comment]
**WORK IN PROGRESS**
