### ISSUE TITLE
FiullScreen: add ordering place holder and capability

### ISSUE THREAD

**Issue by Nick-1979** [PolkaGate/extension#941]
![Screenshot 2024-02-19 at 11 40 49 at night](https://github.com/PolkaGate/extension/assets/46442452/4cefee83-ac12-4877-8da6-d90ed6eb624d)

**Comment by AMIRKHANEF** [comment]
**WORK IN PROGRESS**

**Comment by AMIRKHANEF** [comment]
Related PR posted.
