### ISSUE TITLE
FullScreen: The button design includes distinct colors for both text and icon.

### ISSUE THREAD

**Issue by AMIRKHANEF** [PolkaGate/extension#949]
![image](https://github.com/PolkaGate/extension/assets/75857984/688e6b66-4566-435c-8f0e-dfd7314e9d58)

**Comment by Nick-1979** [comment]
Marin said it is intentional

**Comment by AMIRKHANEF** [comment]
> Marin said it is intentional

That's correct, but I haven't implemented it in my code.

**Comment by AMIRKHANEF** [comment]
**WORK IN PROGRESS**

**Comment by AMIRKHANEF** [comment]
Related PR posted!
