### ISSUE TITLE
FullScreen: getAssetsOnOtherChains.js is unable to fetch ACA token

### ISSUE THREAD

**Issue by AMIRKHANEF** [PolkaGate/extension#970]

**Comment by Nick-1979** [comment]
its is already addressed by commit 20ac0af but only fetches following assets:

<img width="689" alt="Screenshot 2024-03-18 at 00 56 57" src="https://github.com/PolkaGate/extension/assets/46442452/1bd025e7-da0a-4609-93df-c8d5f5a681f0">

**Comment by AMIRKHANEF** [comment]
Cool

**Comment by Nick-1979** [comment]
https://github.com/AcalaNetwork/acala.js/wiki#account-balances
