### ISSUE TITLE
FullScreen: Since new derived/created account is on "any chain" then there is no address show up on home

### ISSUE THREAD

**Issue by Nick-1979** [PolkaGate/extension#978]
<img width="787" alt="Screenshot 2024-02-24 at 11 06 21 in the morning" src="https://github.com/PolkaGate/extension/assets/46442452/56f60e57-8cf1-445d-b1e7-10092c3c2caf">

SUGGESTION: give POLKADOT chain as default to new account

**Comment by Nick-1979** [comment]
I already set the default address to substrate address

**Comment by AMIRKHANEF** [comment]
Hey,
wouldn't it be more logical for the child account to be on the same chain as its parent?
