### ISSUE TITLE
Polkadot/qr-code scanner has lots of issues

### ISSUE THREAD

**Issue by AMIRKHANEF** [PolkaGate/extension#987]
When I tried to add an address from Nova wallet, this happened!

![image](https://github.com/PolkaGate/extension/assets/75857984/70b2cbfa-855c-4c3c-b9e0-8843f8656ce5)

Its scanning capabilities are limited. 

We need to delve into how popular wallets handle QR code information transmission.

**Comment by Nick-1979** [comment]
@AMIRKHANEF  isn't it fixed?

**Comment by AMIRKHANEF** [comment]
yes, I guess all related issues has been fixed!
